FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements-chatbot.txt .

RUN pip install --no-cache-dir \
    -r requirements-chatbot.txt

COPY src/api ./api
COPY src/myChatbot ./myChatbot
COPY src/config.py ./config.py

EXPOSE 8000

CMD ["uvicorn", "api.chatbot_api:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "1"]